# Local Unix socket access
local   all             all                                     trust

# Localhost
host    all             all             127.0.0.1/32            trust
host    all             all             ::1/128                 trust

# Docker bridge network access for local dev stack
host    all             all             0.0.0.0/0               trust
host    all             all             ::/0                    trust
